Update SQLite3 database to PostgreSQL hosted on AWS RDS

diff --git a/bin/insta485db b/bin/insta485db
--- a/bin/insta485db
+++ b/bin/insta485db
@@ -1,87 +1,85 @@
 #!/bin/bash
+# insta485db
+#
+# Andrew DeOrio <awdeorio@umich.edu>
+
+# Path to database file
+UPLOAD_FOLDER=var/uploads
 
 # Stop on errors
-set -Eeuo pipefail
-# Prints commands
-set -x
+set -Eeuxo pipefail
 
 # Sanity check command line options
-usage(){
-    echo "Usage: $0 (create|destroy|reset|dump)"
+usage() {
+echo "Usage: $0 (create|destroy|reset|dump)"
 }
 
 if [ $# -ne 1 ]; then
-    usage
-    exit 1
+usage
+exit 1
 fi
 
-# parse argument. $1 is the first argument
+# Parse command line options
 case $1 in
-    "create")
-        # Runs the sqlite3 command line utility
+"empty")
+    if psql -lqt | grep insta485; then
+    echo "Error: database already exists"
+    exit 1
+    fi
+    createdb --echo insta485
+    psql --echo-errors -d insta485 -f sql/schema.sql
+    mkdir -p ${UPLOAD_FOLDER}
+    ;;
 
-        # Error: if database already exists
-        if [ -d "var/uploads" ]; then
-            echo "Error: database already exists"
-            exit 1
-        fi
+"create")
+    $0 empty
+    psql --echo-errors -d insta485 -f sql/data.sql
+    cp sql/uploads/* ${UPLOAD_FOLDER}/
+    ;;
 
-        mkdir -p var/uploads
-        sqlite3 var/insta485.sqlite3 < sql/schema.sql
-        sqlite3 var/insta485.sqlite3 < sql/data.sql
-        cp sql/uploads/* var/uploads/
-        ;;
+"destroy")
+    dropdb --echo insta485
+    rm -rf ${UPLOAD_FOLDER}
+    ;;
 
-    "destroy")
-        # Delete existing database
-        rm -rf var/insta485.sqlite3 var/uploads
-        ;;
+"reset")
+    $0 destroy
+    $0 create
+    ;;
 
-    "reset")
-        # Does 'destroy' then 'create'
-        rm -rf var/insta485.sqlite3 var/uploads
-        
-        mkdir -p var/uploads
-        sqlite3 var/insta485.sqlite3 < sql/schema.sql
-        sqlite3 var/insta485.sqlite3 < sql/data.sql
-        cp sql/uploads/* var/uploads/
-        ;;
+"dump")
+    TABLES=`psql -d insta485 -c '\x' -c '\dt' | grep Name | awk '{print $3}'`
+    for TABLE in ${TABLES}; do
+    psql -d insta485 -c "\x" -c "SELECT * FROM ${TABLE}"
+    echo
+    done
+    ;;
 
-    "dump")
-        # Prints everything in the database
-        sqlite3 -batch -line var/insta485.sqlite3 'SELECT * FROM comments'
-        sqlite3 -batch -line var/insta485.sqlite3 'SELECT * FROM following'
-        sqlite3 -batch -line var/insta485.sqlite3 'SELECT * FROM likes'
-        sqlite3 -batch -line var/insta485.sqlite3 'SELECT * FROM  posts'
-        sqlite3 -batch -line var/insta485.sqlite3 'SELECT * FROM users'
-        ;;
+"random")
+    SHUF=shuf
+    # If shuf is not on this machine, try to use gshuf instead
+    if ! type shuf 2> /dev/null; then
+    SHUF=gshuf
+    fi
+    DB_FILENAME=var/insta485.sqlite3
+    FILENAMES="122a7d27ca1d7420a1072f695d9290fad4501a41.jpg
+            ad7790405c539894d25ab8dcf0b79eed3341e109.jpg
+            9887e06812ef434d291e4936417d125cd594b38a.jpg
+            2ec7cf8ae158b3b1f40065abfb33e81143707842.jpg"
+    for i in `seq 1 100`; do
+    # echo $FILENAMES      print string
+    # shuf -n1             select one random line from multiline input
+    # awk '{$1=$1;print}'  trim leading and trailing whitespace
 
-    "random")
-        # Generate 100 random posts in the database each with owner awdeorio
-        SHUF=shuf
-        # If shuf is not on this machine, try to use gshuf instead
-        if ! type shuf 2> /dev/null; then
-            SHUF=gshuf
-        fi
-            DB_FILENAME=var/insta485.sqlite3
-            FILENAMES="122a7d27ca1d7420a1072f695d9290fad4501a41.jpg
-                        ad7790405c539894d25ab8dcf0b79eed3341e109.jpg
-                        9887e06812ef434d291e4936417d125cd594b38a.jpg
-                        2ec7cf8ae158b3b1f40065abfb33e81143707842.jpg"
-        for i in `seq 1 100`; do
-            # echo $FILENAMES      print string
-            # shuf -n1             select one random line from multiline input
-            # awk '{$1=$1;print}'  trim leading and trailing whitespace
+    # Use '${SHUF}' instead of 'shuf'
+    FILENAME=`echo "$FILENAMES" | ${SHUF} -n1 | awk '{$1=$1;print}'`
+    OWNER="awdeorio"
+    psql -d insta485 -c "INSERT INTO posts(filename, owner) VALUES('${FILENAME}','${OWNER}');"
+    done
+    ;;
 
-            # Use '${SHUF}' instead of 'shuf'
-            FILENAME=`echo "$FILENAMES" | ${SHUF} -n1 | awk '{$1=$1;print}'`
-            OWNER="awdeorio"
-            sqlite3 -echo -batch ${DB_FILENAME} "INSERT INTO posts(filename, owner) VALUES('${FILENAME}','${OWNER}');"
-        done
-        ;;
-    *)
-        usage
-        exit 1
-        ;;
+*)
+    usage
+    exit 1
+    ;;
 esac
-        
